I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 33, in script
    show dorian_happy happy
Exception: Image 'dorian_happy' does not accept attributes 'happy'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 33, in script
    show dorian_happy happy
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\dev\Downloads\renpy-8.2.0-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'dorian_happy' does not accept attributes 'happy'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
Doki Doki UCSP 1.0
Sun Jan 28 01:28:56 2024
